#File: createPrescription -- [PLACEHOLDER]
#Parameter: Prescription -- [PLACEHOLDER] -- String -- M
#Parameter: Drug -- [PLACEHOLDER] -- String -- M
#Parameter: User -- [PLACEHOLDER] -- String -- M
#Parameter: Day -- [PLACEHOLDER] -- String -- M
#Parameter: Hour -- [PLACEHOLDER] -- String -- M

PREFIX :<http://www.jaatadia.org/IMT/UV2B506Gr2.owl#>
PREFIX base:<http://www.jaatadia.org/IMT/UV2B506Gr2.owl/Individuals#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>

PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>

INSERT {
	base:%%User%% :hasPrescription base:%%Prescription%%.
	base:%%Prescription%% a :Prescription.
	base:%%Prescription%% :hasMedicament base:%%Drug%%.
	base:%%Prescription%% :hasDay "%%Day%%"^^xsd:string.
	base:%%Prescription%% :hasHour "%%Hour%%"^^xsd:string.
	base:%%Prescription%% :isActive "true"^^xsd:string.
}WHERE {
	BIND ( NOW() as ?now )
	BIND ( IRI(CONCAT("base:%%User%%-prescription-", STR(?now))) as ?pres)
}
