#File: setPoints -- [placeHolder]
#Parameter: User -- the consumerKey user data of the person  -- String -- M
#Parameter: Points -- [placeHolder]  -- String -- M
#Parameter: Reason -- [placeHolder]  -- String -- M

PREFIX :<http://www.jaatadia.org/IMT/UV2B506Gr2.owl#>
PREFIX base:<http://www.jaatadia.org/IMT/UV2B506Gr2.owl/Individuals#>
PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>

PREFIX xsd:<http://www.w3.org/2001/XMLSchema#>
PREFIX xml: <http://www.w3.org/XML/1998/namespace>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>


INSERT {
	
	?point a :Points.
	?round :hasPoints ?point.
	?point :hasPointsValue "%%Points%%"^^xsd:int.
	?point :hasPointReason "%%Reason%%"^^xsd:string.

}WHERE {
	BIND ( NOW() as ?now )
	BIND ( IRI(CONCAT("base:%%User%%-point-", STR(?now))) as ?point)
	base:%%User%% :inPersonRound ?round.
}
